version: '3.3'
services:
  app:
    image: containous/whoami
    networks:
      - caddy
    env_file:
      - .env
    labels:
      caddy: "${REAL_DOMAIN}"
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true