version: '3.8'

services:
  app:
    image: nitnelave/lldap:stable
    volumes:
      - data:/data
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
      # ports:
      #   # For the web front-end
      #   - "17170:17170"
    networks:
      - traefik_public
    configs:
      - source: app_config
        target: /data/lldap_config.toml
    environment:
      - LLDAP_JWT_SECRET=/run/secrets/app_jwt
      - LLDAP_LDAP_USER_PASS_FILE=/run/secrets/app_pass
      - LLDAP_LDAP_BASE_DN=dc=dev,dc=test
    secrets:
      - app_pass
      - app_jwt
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lldap.rule=Host(`lldap.dev.test`)"
        - "traefik.http.routers.lldap.entrypoints=https"
        - "traefik.http.routers.lldap.tls=true"
        - "traefik.http.routers.lldap.tls.certresolver=le"
        - "traefik.http.services.lldap.loadbalancer.server.port=17170"

configs:
  app_config:
    file: "./lldap_config.toml"

secrets:
  app_pass:
    file: "./secrets/admin.sec"
  app_jwt:
    file: "./secrets/jwt.sec"

volumes:
  data:
    driver: local

networks:
  traefik_public:
    external: true
