version: "3.2"

# What is this?
#
# This stack exists solely to deploy the caddy_public overlay network, so that
# other stacks can attach to it. This should be idempotent as well.

services:
  scratch:
    image: scratch
    deploy:
      replicas: 0
    networks:
      - public

networks:
  public:
    driver: overlay
    attachable: true
