version: '3.8'
services:
    app:
        image: 'troglobit/inadyn:latest'
        secrets:
            - source: app_config
              target: /etc/inadyn.conf
        deploy:
            mode: replicated
            replicas: 1

secrets:
    app_config:
        file: ./inadyn.conf.sec
