version: "3"
services:
  app:
    build: .
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - config:/config
    networks:
      caddy:
        aliases:
          - rp
    labels:
      caddy.email: ashen@cobaltrain.net
      caddy.acme_dns: vultr $VULTR_TOKEN
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  data:
  config:
