name: boringproxy

services:
  client:
    image: ghcr.io/wgrobler/boringproxy-linux-arm64:latest
    command: client -server bp.$DOMAIN.$TLD -token $BP_TOKEN -client-name rpiavalon -cert-dir /certmagic
    restart: unless-stopped
    networks:
      caddy:
    volumes:
      - certmagic:/certmagic
      - /etc/ssl/certs/:/etc/ssl/certs/:ro

networks:
  caddy:
    external: true

volumes:
  certmagic: