version: '3.7'
services:
  client:
    image: ghcr.io/wgrobler/boringproxy-linux-arm64:latest
    command: client -server bp.$REAL_DOMAIN -token $BP_TOKEN -client-name rpiavalon -cert-dir /certmagic
    restart: unless-stopped
    env_file:
      - .env
    networks:
      caddy:
    volumes:
      - certmagic:/certmagic
      - /etc/ssl/certs/:/etc/ssl/certs/:ro

networks:
  caddy:
    external: true

volumes:
  certmagic: