version: '3.8'

services:
  app:
    image: authelia/authelia
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.rule=Host(`auth.dev.test`)"
        - "traefik.http.routers.authelia.entrypoints=https"
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia_app:9091/api/verify?rd=https://auth.dev.test/"
        - "traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authresponseheaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
    configs:
      - source: app_config
        target: /config/configuration.yml
    secrets:
      - source: lldap_app_pass
        target: /run/secrets/app_pass
    environment:
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/app_pass
    networks:
      - traefik_public

  test_resource:
    image: containous/whoami
    networks:
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.whoami.rule=Host(`whoami.dev.test`)'
        - 'traefik.http.routers.whoami.entrypoints=https'
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true

configs:
  app_config:
    file: ./authelia_config.yaml

secrets:
  lldap_app_pass:
    external: true
