global:
  checkNewVersion: true

api:
  dashboard: true

log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: ashen@cobaltrain.net
      storage: /acme/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlschallenge:

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    watch: true
