name: nextcloud
services:
  app:
    image: nextcloud:latest
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - nc
      default:
    # see: https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/reverse_proxy_configuration.rst  
    labels:
      caddy: nc.$DOMAIN.$TLD
      caddy.header: /*
      caddy.header.Strict-Transport-Security: '"max-age=15552000;"'
      # caddy.header.Content-Security-Policy: "form-action 'self' https://collabora.14641avalon.group;"
      caddy.redir_0: /.well-known/carddav /remote.php/dav 301
      caddy.redir_1: /.well-known/caldav /remote.php/dav 301
      caddy.redir_2: /.well-known/webfinger /index.php/.well-known/webfinger 301
      caddy.redir_3: /.well-known/nodeinfo  /index.php/.well-known/nodeinfo 301
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
      - ncdata:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=$NC_DB_PASS
      - REDIS_HOST=redis
      - SMTP_HOST=smtp.sendgrid.net 
      - SMTP_NAME=apikey
      - SMTP_PASSWORD=$SMTP_PASS
      # See: https://hub.docker.com/_/nextcloud/
      - APACHE_DISABLE_REWRITE_IP=1
      # See: https://github.com/nextcloud/documentation/issues/7005
      # and: https://old.reddit.com/r/NextCloud/comments/s3skdn/nextcloud_behind_caddy_as_a_reverse_proxy_using/hsnj5wh/
      - NEXTCLOUD_TRUSTED_DOMAINS=nc.$DOMAIN.$TLD
      - TRUSTED_PROXIES=$TRUSTED_PROXIES
      - OVERWRITEHOST=nc.$DOMAIN.$TLD
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://nc.$DOMAIN.$TLD
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: $NC_DB_PASS
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
    
  redis:
    image: redis:latest
    restart: unless-stopped 
    networks:
      - default

  cron:
    image: nextcloud:latest
    restart: always
    volumes:
      - ncdata:/var/www/html
    entrypoint: /cron.sh
    networks:
      - default

networks:
  caddy:
    external: true
  default:

volumes:
  ncdata:
  dbdata:
