version: '3.7'
services:
  client:
    build: .
    command: server -admin-domain bp.$REAL_DOMAIN -cert-dir /certmagic -acme-email $EMAIL -acme-certificate-authority https://acme.zerossl.com/v2/DV90
    restart: unless-stopped
    env_file:
      - ../boringproxy/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - certmagic:/certmagic
      - /etc/ssl/certs/:/etc/ssl/certs/:ro

volumes:
  certmagic: